name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake.svg"
          add: dist/snake.svg
          push_args: --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
