name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: generate
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          add: dist/snake.svg
